# Site settings
title: phpbin
email: andrew@akenn.org
description: > # this means to ignore newlines until "baseurl:"
  Run php code in the browser
baseurl: "/phpbin/" # the subpath of your site, e.g. /blog/
url: "http://akenn.github.io" # the base hostname & protocol for your site
twitter_username: akenn_
github_username:  akenn

# Build settings
markdown: kramdown
